# Generated by Django 3.2.7 on 2021-09-21 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='tipo',
            field=models.IntegerField(default=2),
        ),
    ]
